---
- name: install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: install main site VirtualHost
  template:
    src: ../files/vhost.conf.j2
    dest: /etc/apache2/sites-available/{{ ansible_fqdn }}.conf
    owner: root
    group: root
    mode: 0644

- name: disable default site
  command: a2dissite 000-default

- name: enable main site
  command: a2ensite {{ ansible_fqdn }}
  notify:
  - restart apache2
