---
- name: install django
  pip:
    name: django
    executable: pip3
    state: present

- name: install psycopg2
  pip:
    name: psycopg2
    executable: pip3
    state: present

- name: install mod_wsgi
  apt:
    name: libapache2-mod-wsgi-py3
    state: present

- name: enable mod_wsgi
  apache2_module:
    name: wsgi
    state: present
