---
- name: remove letsencrypt
  apt:
    name: letsencrypt
    state: absent
    update_cache: yes

- name: install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: no

- name: add signing key for certbot repo
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 75BCA694

- name: enable latest stable repo for certbot
  apt_repository:
    repo: deb http://ppa.launchpad.net/certbot/certbot/ubuntu {{ ansible_distribution_release }} main
    filename: certbot
    state: present
    update_cache: yes

- name: install python-certbot-apache
  apt:
    name: python-certbot-apache
    state: present
    update_cache: no

- name: create and install SSL certificates
  command: certbot --apache --domains {{ certbot_domains }} --email {{ certbot_email }} {{ certbot_opts }}

- name: setup cron job to autorenew cert
  cron:
    name: renew SSL cert every {{ certbot_renew_freq }} months
    job: certbot renew
    month: "*/{{ certbot_renew_freq }}"
    day: "{{ certbot_renew_day }}"
    hour: "{{ certbot_renew_hour }}"
    minute: "{{ certbot_renew_minute }}"
    state: present
