---
- name: create Jupyter user {{ jupyter_system_user }}
  user:
    name: "{{ jupyter_system_user }}"
    groups: "{{ apache_group }},staff"
    append: yes
    system: yes
    home: "{{ jupyter_system_home }}"

- name: create {{ jupyter_system_home }}/.jupyter
  file:
    path: "{{ jupyter_system_home }}/.jupyter"
    state: directory
    mode: 0755

- name: create Jupyter config file
  template:
    src: ../files/jupyter_notebook_config.py.j2
    dest: "{{ jupyter_system_home }}/.jupyter/jupyter_notebook_config.py"
    owner: jupyter
    group: jupyter
    mode: 0644
