---
- name: create /usr/lib/systemd/system
  file:
    path: /usr/lib/systemd/system
    state: directory
    owner: root
    group: root
    mode: 0755

# thanks to https://gist.github.com/whophil/5a2eab328d2f8c16bb31c9ceaf23164f for the template
- name: create Jupyter systemd service
  template:
    src: ../files/jupyter.service.j2
    dest: /usr/lib/systemd/system/jupyter.service
    owner: root
    group: root
    mode: 0644

- name: enable jupyter.service
  systemd:
    name: jupyter
    daemon_reload: yes
    enabled: yes
    state: started
