---
- name: install pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: upgrade pip3
  pip:
    name: pip
    executable: pip3
    state: latest

- name: install django
  pip:
    name: django
    executable: pip3
    state: present
