---
- name: remove vim-tiny
  apt:
    name: vim-tiny
    state: absent
    purge: true

- name: install vim-nox
  apt:
    name: vim-nox
    state: latest
    update_cache: yes

- name: install vim-pathogen
  apt:
    name: vim-pathogen
    state: latest
    update_cache: no

- name: install fish
  apt:
    name: fish
    state: latest
    update_cache: no
