---
- name: create sudoer "{{ common_user }}"
  user:
    name: "{{ common_user }}"
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    shell: /usr/bin/zsh

- name: install Oh My Zsh
  script: ../files/install-oh-my-zsh.sh
  become: yes
  become_user: "{{ common_user }}"
