---
- name: ensure sudoer alan, with shell fish (hyuk hyuk)
  user:
    name: alan
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    shell: /usr/bin/fish

# - name: install oh-my-fish
#   raw: curl -L http://get.oh-my.fish | fish
#   become: yes
#   become_user: alan
