---
- name: ensure sudoer "{{ common_user }}"
  user:
    name: "{{ common_user }}"
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 4096
    shell: /usr/bin/fish

- name: install Oh My Fish
  script: ../files/install-omf.sh
  become: yes
  become_user: "{{ common_user }}"

- name: customize Oh My Fish
  script: ../files/customize.fish
  become: yes
  become_user: "{{ common_user }}"
